import type { Announcement, Event, Notification, User, TeamsMessage } from "./types"

export const mockUser: User = {
  id: "1",
  name: "John Smith",
  email: "john.smith@company.com",
  role: "admin",
  department: "engineering",
  avatar: "/professional-man-avatar.png",
  isAuthenticated: true,
}

export const mockAnnouncements: Announcement[] = [
  {
    id: "1",
    title: "Q4 Company Performance Update",
    titleJa: "第4四半期 会社業績アップデート",
    content:
      "We are pleased to announce that our Q4 results have exceeded expectations. Revenue grew by 25% compared to last quarter, and we have successfully launched three new products. Thank you all for your hard work and dedication.",
    contentJa:
      "第4四半期の業績が予想を上回りましたことをお知らせいたします。売上は前四半期比25%増加し、3つの新製品の発売に成功しました。皆様のご尽力に感謝申し上げます。",
    priority: "ceo",
    department: "all",
    status: "approved",
    author: "Sarah Johnson, CEO",
    authorId: "ceo-1",
    createdAt: "2024-01-15T09:00:00Z",
    updatedAt: "2024-01-15T09:00:00Z",
    imageUrl: "/business-growth-chart.png",
    isAiGenerated: false,
    aiOverridden: false,
  },
  {
    id: "2",
    title: "System Maintenance - This Weekend",
    titleJa: "システムメンテナンス - 今週末",
    content:
      "Critical system maintenance will be performed this Saturday from 2 AM to 6 AM JST. All internal systems including email and file sharing will be temporarily unavailable. Please save your work before Friday evening.",
    contentJa:
      "今週土曜日の午前2時から午前6時（日本時間）まで、重要なシステムメンテナンスを実施いたします。メールやファイル共有を含むすべての社内システムが一時的に利用できなくなります。金曜日の夕方までに作業を保存してください。",
    priority: "urgent",
    department: "all",
    status: "approved",
    author: "IT Department",
    authorId: "it-1",
    createdAt: "2024-01-14T14:30:00Z",
    updatedAt: "2024-01-14T14:30:00Z",
    isAiGenerated: false,
    aiOverridden: false,
  },
  {
    id: "3",
    title: "New Health Insurance Benefits",
    titleJa: "新しい健康保険給付",
    content:
      "Starting February 1st, we are expanding our health insurance coverage to include mental health services, dental care, and vision care. Please review the updated benefits package in the HR portal.",
    contentJa:
      "2月1日より、健康保険の適用範囲を拡大し、メンタルヘルスサービス、歯科治療、視力ケアが含まれるようになります。HRポータルで更新された給付パッケージをご確認ください。",
    priority: "important",
    department: "all",
    status: "approved",
    author: "HR Team",
    authorId: "hr-1",
    createdAt: "2024-01-13T10:00:00Z",
    updatedAt: "2024-01-13T10:00:00Z",
    isAiGenerated: true,
    aiOverridden: false,
  },
  {
    id: "4",
    title: "Engineering Team Sprint Review",
    titleJa: "エンジニアリングチーム スプリントレビュー",
    content:
      "The engineering team has completed Sprint 24 with 95% of planned features delivered. Key highlights include the new authentication system, performance improvements, and mobile app updates.",
    contentJa:
      "エンジニアリングチームはスプリント24を完了し、計画された機能の95%を提供しました。主なハイライトには、新しい認証システム、パフォーマンスの改善、モバイルアプリの更新が含まれます。",
    priority: "general",
    department: "engineering",
    status: "approved",
    author: "Mike Chen",
    authorId: "eng-1",
    createdAt: "2024-01-12T16:00:00Z",
    updatedAt: "2024-01-12T16:00:00Z",
    isAiGenerated: true,
    aiOverridden: true,
  },
  {
    id: "5",
    title: "Marketing Campaign Launch",
    titleJa: "マーケティングキャンペーン開始",
    content:
      'Our new brand campaign "Innovation Forward" launches next Monday across all digital channels. Marketing team members please join the kickoff meeting at 10 AM.',
    contentJa:
      "新しいブランドキャンペーン「Innovation Forward」が来週月曜日にすべてのデジタルチャネルで開始されます。マーケティングチームのメンバーは午前10時のキックオフミーティングにご参加ください。",
    priority: "event",
    department: "marketing",
    status: "approved",
    author: "Lisa Wang",
    authorId: "mkt-1",
    createdAt: "2024-01-11T11:00:00Z",
    updatedAt: "2024-01-11T11:00:00Z",
    imageUrl: "/marketing-campaign-colorful.jpg",
    isAiGenerated: false,
    aiOverridden: false,
  },
  {
    id: "6",
    title: "Budget Submission Deadline",
    titleJa: "予算提出締め切り",
    content:
      "All department heads are reminded that the FY2024 budget submissions are due by January 31st. Please ensure all projections and justifications are included in your submissions.",
    contentJa:
      "すべての部門長に、2024年度予算の提出期限が1月31日であることをお知らせします。すべての予測と根拠を提出物に含めてください。",
    priority: "deadline",
    department: "finance",
    status: "approved",
    author: "Finance Team",
    authorId: "fin-1",
    createdAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-01-10T09:00:00Z",
    isAiGenerated: false,
    aiOverridden: false,
  },
]

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "All-Hands Meeting",
    titleJa: "全社ミーティング",
    description: "Quarterly all-hands meeting with CEO presentation and Q&A session.",
    descriptionJa: "CEOプレゼンテーションとQ&Aセッションを含む四半期全社ミーティング。",
    startDate: "2024-01-20T14:00:00Z",
    endDate: "2024-01-20T16:00:00Z",
    location: "Main Conference Room / Zoom",
    department: "all",
    priority: "important",
    isRecurring: true,
    recurrencePattern: "quarterly",
    reminderSent: false,
    createdBy: "HR Team",
  },
  {
    id: "2",
    title: "Product Launch Celebration",
    titleJa: "製品発売祝賀会",
    description: "Celebration party for the successful launch of our new flagship product.",
    descriptionJa: "新しいフラッグシップ製品の発売成功を祝うパーティー。",
    startDate: "2024-01-25T18:00:00Z",
    endDate: "2024-01-25T21:00:00Z",
    location: "Rooftop Terrace",
    department: "all",
    priority: "event",
    isRecurring: false,
    reminderSent: false,
    createdBy: "Events Team",
  },
  {
    id: "3",
    title: "Engineering Tech Talk",
    titleJa: "エンジニアリング技術講演",
    description: 'Monthly tech talk series - this month: "Building Scalable Microservices"',
    descriptionJa: "月例技術講演シリーズ - 今月:「スケーラブルなマイクロサービスの構築」",
    startDate: "2024-01-18T15:00:00Z",
    endDate: "2024-01-18T16:30:00Z",
    location: "Engineering Floor / Teams",
    department: "engineering",
    priority: "general",
    isRecurring: true,
    recurrencePattern: "monthly",
    reminderSent: true,
    createdBy: "Engineering Lead",
  },
  {
    id: "4",
    title: "Sales Training Workshop",
    titleJa: "営業研修ワークショップ",
    description: "Advanced negotiation techniques and closing strategies workshop.",
    descriptionJa: "高度な交渉テクニックとクロージング戦略のワークショップ。",
    startDate: "2024-01-22T10:00:00Z",
    endDate: "2024-01-22T17:00:00Z",
    location: "Training Room B",
    department: "sales",
    priority: "important",
    isRecurring: false,
    reminderSent: false,
    createdBy: "Sales Director",
  },
]

export const mockNotifications: Notification[] = [
  {
    id: "1",
    title: "New Announcement",
    titleJa: "新しいお知らせ",
    message: "CEO has posted a new company update",
    messageJa: "CEOが新しい会社のアップデートを投稿しました",
    type: "announcement",
    isRead: false,
    createdAt: "2024-01-15T09:05:00Z",
    link: "/announcements/1",
  },
  {
    id: "2",
    title: "Event Reminder",
    titleJa: "イベントリマインダー",
    message: "All-Hands Meeting starts in 1 hour",
    messageJa: "全社ミーティングが1時間後に始まります",
    type: "reminder",
    isRead: false,
    createdAt: "2024-01-20T13:00:00Z",
    link: "/events/1",
  },
  {
    id: "3",
    title: "System Update",
    titleJa: "システムアップデート",
    message: "Portal has been updated with new features",
    messageJa: "ポータルが新機能で更新されました",
    type: "system",
    isRead: true,
    createdAt: "2024-01-14T08:00:00Z",
  },
]

export const mockTeamsMessages: TeamsMessage[] = [
  {
    id: "1",
    content: "Great news everyone! We just closed the biggest deal of the quarter.",
    from: "Sales Team",
    timestamp: "2024-01-15T10:30:00Z",
    channelName: "Sales Announcements",
  },
  {
    id: "2",
    content: "Reminder: Code freeze for v2.0 is tomorrow at 5 PM.",
    from: "Engineering Lead",
    timestamp: "2024-01-15T11:00:00Z",
    channelName: "Engineering Updates",
  },
  {
    id: "3",
    content: "The new office snacks have arrived! Check the kitchen.",
    from: "Office Manager",
    timestamp: "2024-01-15T14:00:00Z",
    channelName: "General",
  },
]
